version: '3.8'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: xburn-metabase
    ports:
      - "${METABASE_PORT:-3000}:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase_app
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: metabase-db
    depends_on:
      metabase-db:
        condition: service_healthy
    networks:
      - metabase_network
    volumes:
      - metabase_data:/metabase.db

  metabase-db:
    image: postgres:15-alpine
    container_name: xburn-metabase-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metabase_app
    volumes:
      - metabase_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - metabase_network

volumes:
  metabase_data:
  metabase_postgres_data:

networks:
  metabase_network:
    name: metabase_network 